version: '3.8'
services:
  mic-analytics-processor:
    build:
      context: .
      dockerfile: mic-analytics-processor/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
    networks:
      - stream-analitics-network

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - stream-analitics-network
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - dbdata:/data/db
    networks:
      - stream-analitics-network
networks:
  stream-analitics-network:
    driver: bridge
volumes:
  dbdata:
