version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017

