version: '2.1'
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27017:27017
