FROM amazoncorretto:17-alpine-jdk
MAINTAINER Franciscogonmir
COPY mic-analytics-processor/target/mic-analytics-processor-1.0.0.jar /app/mic-analytics-processor-1.0.0.jar
ENTRYPOINT ["java","-jar","/app/mic-analytics-processor-1.0.0.jar"]
